$(document).ready(function(){

    // Form sumbitted
    $("#myForm").submit(function(event){
        
        var url = ""; // the script where you handle the form input.
        
            $.ajax({
                   type: "POST",
                   url: url,
                   data: $("#myForm").serialize(), // serializes the form's elements.
                   success: function(data)
                   {
                        alert('Data Drom Server: '+data); // show response from the python server.
                       
                        //succsfull connection
                        if(data == 'success'){
                                                       
                            // ------ saving cookies that generated by the server 
                            document.cookie = "username=DonMatanon; expires=Fri, 06 Oct 2017 14:21:00 UTC;"
                            window.location.replace("http://localhost/myMainApp.html");
                        }
                        //bad connection 
                        else if(data == 'failed'){
                            $('#loginpop').show()
                            $('#username').val('');
                            $('#pwd').val('');
                        }
                        //db is not connectig
                        else{
                            alert('Might Be a problem with the server');
                        }
                            
                    }
                 });
                 event.preventDefault(); // avoid to execute the actual submit of the form.
        
                
        
        });

       
       
        // Check boxes logics
        $(":checkbox").change(function(e) {
            
            
            var checkboxId = $(this).attr('id');

            // if family check all checkbox changed
            if (checkboxId == 'checkMain2xx' || checkboxId == 'checkMain3xx' || checkboxId == 'checkMain4xx' || checkboxId == 'checkMain5xx' || checkboxId == 'checkMain6xx' || checkboxId == 'checkMain7xx' ){
                
                var table= $(e.target).closest('table');
                
                //change all the family checkboxes
                $('td input:checkbox',table).prop('checked',this.checked);               
                
                if(!e.target.checked)
                {
                    deleteRulesPanel(table);
                }
                else
                {
                    deleteRulesPanel(table);
                    addToRulesPanel(table);
                }    
            }
            else{ // specific checkbox pushed
                if(!e.target.checked)
                {
                    deleteRulesPanel(e);
                    
                }
                else{
                    deleteRulesPanel(e);
                    addToRulesPanel(e);
                }
                

            }
                

        });
            

        //clear the rules from panel
        function deleteRulesPanel(params)
        {
            console.log('in deleteRulesPanel');
            //delete specific rule from panel
            if($(params.target).attr('type') == 'checkbox'){
                $("#schedRulesPanel > p" ).each(function() {                   
                    if($(this).text() == $(params.target).parent().parent().parent().children().eq(1).text()+ ' '+ $(params.target).parent().parent().parent().children().eq(2).text() ){
                        $(this).remove();
                    }
                      
                  });
            }
            else{
                //delete all rules from same family from panel
                console.log($(params).attr('id').slice(0,1));
                $("#schedRulesPanel > p" ).each(function() { 
                    if($(this).text().slice(0,1) == $(params).attr('id').slice(0,1) ){
                        $(this).remove();
                    }
                });
            } 
        }
           
       

        function addToRulesPanel(params)
        {   

            console.log('in addToRulesPanel');
            // add specific rule to panel
            if($(params.target).attr('type') == 'checkbox'){
                console.log('in addToRulesPanel in if');
                $("#schedRulesPanel").append('<p>'+$(params.target).parent().parent().parent().children().eq(1).text()+ ' '+ $(params.target).parent().parent().parent().children().eq(2).text() + '</p>');
            }
            else{ //add all family rules to panel
                console.log('in addToRulesPanel in else');
                $(params).find('tr').each(function(){
                    if($(this).children().eq(1).text().slice(0,1)!='R')
                    {
                        $("#schedRulesPanel").append('<p>'+$(this).children().eq(1).text() +' '+ $(this).children().eq(2).text()+'</p>');
                    }
                 });
            }
                
            
            
           
        }

        
    

});